### ISSUE TITLE
e2e tests (integrated with backend)

### ISSUE THREAD

**Issue by iomn** [aktionskarten/aktionskarten.js#25]
Add end-to-end tests for aktionskarten.js (together with backend). Currently missing are tests and docker compose files (to actually have the backend running for travis and the tests). See the follwing:

* tests (through ava) WIP are located at https://github.com/aktionskarten/aktionskarten.js/tree/feature/tests
* docker compose file for backend https://github.com/aktionskarten/backend/issues/14

**Comment by kohllisti** [comment]
please make sure to use the same testing framework as [aktionskarten/frontend](https://github.com/aktionskarten/frontend/)
