### ISSUE TITLE
fix travis deployment

### ISSUE THREAD

**Issue by iomn** [aktionskarten/aktionskarten.js#37]
At the moment our travis deployment configurations fails (see https://travis-ci.com/aktionskarten/aktionskarten.js/builds/149041488 ).

```
0.00s Install deployment dependencies
0.00s Authenticate deployment
npm version: 6.7.0
Authenticated with API token Dzd2****************
~/.npmrc size: 717
$ npm config set registry "https://registry.npmjs.org"

0.00s Setup deployment
0.00s Prepare deployment
2.00s Run deployment
(..)
npm ERR! code E401
npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/aktionskarten.js - You must be logged in to publish packages.

Failed to publish
failed to deploy
```
We switched to v2 recently because of another bug in v1 (error : "No stash entries found. missing api_key failed to deploy" - see https://travis-ci.community/t/no-stash-entries-found-missing-api-key-failed-to-deploy/6029 and https://travis-ci.com/aktionskarten/aktionskarten.js/builds/148811328 )

**Comment by waschbeer** [comment]
Should works now
